name: celer
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Flutter-Quest/celer

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  benchmark_harness: ^2.2.1
  dart_console: ^1.1.2
  chalkdart: ^2.0.9

dependencies:
  path: ^1.8.3
